package com.playsawdust.chipper.glow.gl;

import org.lwjgl.opengl.GL20;
import org.lwjgl.opengl.GL30;
import org.lwjgl.opengl.GL40;
import org.lwjgl.opengl.GL46;
import org.lwjgl.opengl.AMDGPUShaderInt64;

/** Exhaustive enum of all types available to &lt;= GL20 */
public enum GLType {
	BOOLEAN(GL20.GL_BOOL),
	VEC2_BOOLEAN(GL20.GL_BOOL_VEC2),
	VEC3_BOOLEAN(GL20.GL_BOOL_VEC3),
	VEC4_BOOLEAN(GL20.GL_BOOL_VEC4),
	
	BYTE(GL20.GL_BYTE),
	UBYTE(GL20.GL_UNSIGNED_BYTE),
	
	SHORT(GL20.GL_SHORT),
	VEC2_SHORT(AMDGPUShaderInt64.GL_INT16_VEC2_NV),
	VEC3_SHORT(AMDGPUShaderInt64.GL_INT16_VEC3_NV),
	VEC4_SHORT(AMDGPUShaderInt64.GL_INT16_VEC4_NV),
	USHORT(GL20.GL_UNSIGNED_SHORT),
	
	INT(GL20.GL_INT),
	VEC2I(GL20.GL_INT_VEC2),
	VEC3I(GL20.GL_INT_VEC3),
	VEC4I(GL20.GL_INT_VEC4),
	UINT(GL20.GL_UNSIGNED_INT),
	
	INT64(AMDGPUShaderInt64.GL_INT64_NV),
	VEC2L(AMDGPUShaderInt64.GL_INT64_VEC2_NV),
	VEC3L(AMDGPUShaderInt64.GL_INT64_VEC3_NV),
	VEC4L(AMDGPUShaderInt64.GL_INT64_VEC4_NV),
	UINT64(AMDGPUShaderInt64.GL_UNSIGNED_INT64_NV),
	
	HALF_FLOAT(GL30.GL_HALF_FLOAT),
	
	
	FLOAT(GL20.GL_FLOAT),
	VEC2F(GL20.GL_FLOAT_VEC2),
	VEC3F(GL20.GL_FLOAT_VEC3),
	VEC4F(GL20.GL_FLOAT_VEC4),
	MAT2F(GL20.GL_FLOAT_MAT2),
	MAT3F(GL20.GL_FLOAT_MAT3),
	MAT4F(GL20.GL_FLOAT_MAT4),
	
	DOUBLE(GL20.GL_DOUBLE),
	VEC2D(GL40.GL_DOUBLE_VEC2),
	VEC3D(GL40.GL_DOUBLE_VEC3),
	VEC4D(GL40.GL_DOUBLE_VEC4),
	MAT2D(GL40.GL_DOUBLE_MAT2),
	MAT3D(GL40.GL_DOUBLE_MAT3),
	MAT4D(GL40.GL_DOUBLE_MAT4),
	
	//reserved by library
	UNKNOWN(-1);
	
	private int glConstant;
	
	GLType(int glConstant) {
		this.glConstant = glConstant;
	}
	
	public static GLType of(int i) {
		for(GLType t : values()) {
			if (t.glConstant == i) return t;
		}
		
		return UNKNOWN;
	}
	
}